server.servlet.contextPath=/
server.port=8080

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRESQL_DATABASE}
spring.datasource.username=${POSTGRESQL_USERNAME}
spring.datasource.password=${POSTGRESQL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Minio config
minio.endpoint=${MINIO_ENDPOINT:http://localhost}
minio.port=9000
minio.secure=false
minio.user=${MINIO_USERNAME}
minio.password=${MINIO_PASSWORD}


# Swagger UI Configuration
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Api Docs Configuration
springdoc.api-docs.path=/api-docs
springdoc.api-docs.version=OPENAPI_3_0
springdoc.api-docs.enabled=true

# JPA DataBase Configuration
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Spring multipart file configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=500MB
spring.servlet.multipart.file-size-threshold=5MB
spring.servlet.multipart.resolve-lazily=true

# Server error Configuration
server.error.include-message=always
server.error.include-stacktrace=never